### ISSUE TITLE
What's your favorite ES2015 feature and why?

### ISSUE THREAD

**Issue by arthurvr** [Qix-/ama#2]

**Comment by Qix-** [comment]
Symbols, probably. I write a lot of "meta-code" - descriptors, reflection, etc. - and Symbols will be a nice new tool in the box. They're the answer to _Why can't I add custom properties to descriptors to change a description of an object?_ and will allow me to do some cool stuff with my existing [API generation](/Qix-/eloquent) modules, for instance.
